services:
  rotato:
    image: ghcr.io/msalman5230/rotato:latest
    container_name: rotato
    restart: unless-stopped
    ports:
      - "8997:8990"
    environment:
      - ENV_FILE=/app/data/.env
    volumes:
      - /mnt/user/appdata/rotato:/app/data


